name: Update EPG
on:
  schedule:
    - cron: '0 4 * * *' # Runs every day at 4:00 AM
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Filter Script
        run: python filter_epg.py
      - name: Commit and Push
        run: |
          git config --global user.name "EPG-Bot"
          git config --global user.email "bot@github.com"
          # This command adds both files specifically
          git add custom_guide.xml custom_guide.xml.gz
          # The '|| exit 0' prevents the "error" if nothing changed
          git commit -m "Update EPG files" || exit 0
          git push

