name: Update EPG
on:
  schedule:
    - cron: '0 21 * * *' # Runs every day at 9:00 PM
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Filter Script
        run: python filter_epg.py
      - name: Commit and Push
        run: |
          git config --global user.name "EPG-Bot"
          git config --global user.email "bot@github.com"
          git add custom_guide.xml custom_guide.xml.gz
          
          # This variable grabs the last line of the python output
          STATS=$(python filter_epg.py | tail -n 2 | head -n 1)
          
          git commit -m "EPG Auto-Update: $STATS" || exit 0
          git push
      - name: Backup to Dropbox
        env:
          DBX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: |
          # Upload the plain XML
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $DBX_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/EPG_Backups/custom_guide.xml\",\"mode\": \"overwrite\"}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @custom_guide.xml

          # Upload the Gzipped version
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $DBX_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\": \"/EPG_Backups/custom_guide.xml.gz\",\"mode\": \"overwrite\"}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @custom_guide.xml.gz
            
